### ISSUE TITLE
Why would the `reachable` boolean be false?

### ISSUE THREAD

**Issue by flippyhead** [sindresorhus/is-reachable#11]
I don't understand why the `reachable` boolean should be false when the promise is fired. I'm only checking a single host.

**Comment by sindresorhus** [comment]
Can you elaborate? What is unexpected about that? If it's false, it means it's not reachable.

**Comment by flippyhead** [comment]
Sorry, I was confused. I assumed it would not fire the `then` callback, but instead `error` in case the site was not `isReachable`. Thanks!
