### ISSUE TITLE
How to check if an url is uncreachble ?

### ISSUE THREAD

**Issue by andibastian** [sindresorhus/is-reachable#15]
hello, i'm confuse, how to use this great script to check if an url is unreachable ?

I'm write like these :

isReachable('google.com').then(reachable => {
    //createWindow();
    if(reachable==true){
      console.log("OK")
    }
    else {
      console.log("Error")
    }
  });

but, the result is always not stable, sometime true, sometime false

**Comment by sindresorhus** [comment]
I guesss you have some interference on your connection or something. You probably want the higher-level module [`is-online`](https://github.com/sindresorhus/is-online) instead though.

**Comment by Adiii717** [comment]
I also want to check if URL is not reachable and I also want to increase the timeout. I do want to create an issue because it's not an issue and there is no clear mention in the documentation. But just mention like its dependency module https://www.npmjs.com/package/is-port-reachable
Thanks

**Comment by silverwind** [comment]
> check if URL is not reachable

Something like this (in an async function). The value on timeout depends on how fast the target server can handshake, but this should typically complete under a second:

````js
const notReachable = !(await isReachable(url, {timeout: 1000}));
````
