### ISSUE TITLE
[Q] Transpiling to ES5 for browser compability

### ISSUE THREAD

**Issue by andys8** [sindresorhus/is-reachable#16]
Hi @sindresorhus, I'm wondering why this library is using ES6 and is not transpiling to ES5. Isn't that the common behavior nowadays? Is it intentional not to do it?

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446

**Comment by andys8** [comment]
Thanks for the quick answer. Do you think the description text could be misleading?

![image](https://cloud.githubusercontent.com/assets/13085980/24102709/1937cb20-0d7d-11e7-9e01-d2767f13a48e.png)

**Comment by SamVerschueren** [comment]
Okay, didn't check the repository to be honest before I answered. But there is a [`browser.js`](https://github.com/sindresorhus/is-reachable/blob/master/browser.js) file so make sure to use that one.

**Comment by silverwind** [comment]
Not sure what your setup is, but you could use something like https://github.com/babel/babelify to browserify and transpile it to ES5.

**Comment by andys8** [comment]
I'm using webpack and will transpile the library to es5 using Babel (or replace it). But because this is the first time I had to do this for a npm dependency, I wanted to ask you about it. Correct me if I'm wrong, but I think it's not common. But I see the point that this library is targeting nodejs. So thanks for your support.

**Comment by silverwind** [comment]
I think @sindresorhus expects the user to transpile, but I could be wrong.

**Comment by SamVerschueren** [comment]
It's all in the AMA question I linked to in my first reply.
