### ISSUE TITLE
Ftp protocol not working

### ISSUE THREAD

**Issue by mtuchi** [sindresorhus/is-reachable#20]
Hello am trying to use this library to ftp to my device 
am still getting `false`. Any suggestion

**Comment by silverwind** [comment]
Check with `nc`, `telnet`, `ftp` or similar tools first. Most certainly not an issue with this module:

```
$ node -p 'require(".")("ftp://speedtest.tele2.net").then(console.log)'
Promise { <pending> }
true
```
