### ISSUE TITLE
FYI: create-react-app cannot minify this package

### ISSUE THREAD

**Issue by danielmahon** [sindresorhus/is-reachable#23]
When trying to include this package in a `create-react-app` project, upon builds it complains that `browser.js` is not ES5 friendly so it cannot minify it, which breaks the build.

See: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.
