### ISSUE TITLE
Is it compatible with ES5 and react 16

### ISSUE THREAD

**Issue by Venmathi2510** [sindresorhus/is-reachable#34]
Hi,
I use ES5. it throws me the following error. could u plz help me on it.

ERROR in ./~/is-reachable/browser.js
You may need an appropriate loader to handle this file type.                     
SyntaxError: Unexpected token (8:23)
--

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
