### ISSUE TITLE
A question about self-signed cert used in https case

### ISSUE THREAD

**Issue by royling** [sindresorhus/is-reachable#36]
If a self-signed cert is used in the target server, the browsers require user's override to handle the requests. In Chrome, it gives `NET::ERR_CERT_AUTHORITY_INVALID` first.

In this case, this lib (for browser) would not work. Right?
I think it would be good to note this in the doc, I can submit a PR if acceptable.

**Comment by sindresorhus** [comment]
I don't really see why that needs to be documented here. It's just basic XHR/fetch behavior. It's not specific to this module.
