### ISSUE TITLE
is-reachable is huge since v2.2.0

### ISSUE THREAD

**Issue by nikku** [sindresorhus/is-reachable#37]
![image](https://user-images.githubusercontent.com/58601/63773455-78b48400-c8db-11e9-9952-ca81bab0da52.png)

I had to pin my `npx` installable script to version `2.1.0` to not download two megabytes of utility.

Looks like `port-numbers` makes the bundle size explode. Is this dependency really necessary?

Cf. [v2.1.0...v2.2.0](https://github.com/sindresorhus/is-reachable/compare/v2.1.0...v2.2.0).

**Comment by sindresorhus** [comment]
// @silverwind

**Comment by silverwind** [comment]
`port-numbers` is for:

> Well-known protocols are supported (for example: ftp://, mysql://, redis:// and more).

It does include two huge JSON files to support thousands of protocols, but I'm happy if you want to remove the dependency to reduce size in a `semver-major`. It's rather unnecessary and not many people are probably using those protocol prefixes.

**Comment by nikku** [comment]
@silverwind Thanks for clarifying.

For me this depends on where you'd see this library: Should it be focused and _micro_ or should it support an extensive set of features.

I personally check for reach-ability of URLs only so for me that additional feature has (and had) no value.

**Comment by silverwind** [comment]
`postgresql://host` is also a URL and the library would need to know that that means port 6379. I'm thinking the primary use of the module should be `host:port`, with port being a number, but we do have a special exception for HTTP/HTTPS because it's so common.

**Comment by nikku** [comment]
Yea, sorry. When writing URL I actually meant HTTP(S) URLs. Makes perfect sense to me.
