### ISSUE TITLE
Needs better documentation to avoid mistakes

### ISSUE THREAD

**Issue by leopucci** [sindresorhus/is-reachable#57]
Hey there
I´m getting false return of true on isReachable(http://localhost:2000) while the server is down
Windows 10

**Comment by leopucci** [comment]
This is happening because of the fact of async await. 
Could you clarify your docs like isOnline?
```
It returns a promise so I need to use then()

isReachable(http://localhost:2000)).then() not using a basic if(isReachable(http://localhost:2000))
```

**Comment by leopucci** [comment]
https://github.com/sindresorhus/is-reachable/pull/58

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/is-reachable/pull/58#issuecomment-1122658459
