### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/is-reachable#7]
Spawned off https://github.com/sindresorhus/is-online/issues/18 and https://github.com/sindresorhus/is-online-cli/issues/1:

We should investigate adding support for a system-configured proxy through a HTTP agent that supports SOCKS proxies, like [got](https://github.com/sindresorhus/got#proxies).

I assume the hard part about this is a cross-platform way of detecting whether there is a active system proxy. In macOS, that can be shown through `networksetup -getwebproxy "Wi-Fi"` for example.

**Comment by sindresorhus** [comment]
Closing as it's not something I care about.
